#!/usr/bin/env node
// gen-index.js — Folio site index generator
//
// Reads <site-root>/.folio/site.json and emits <site-root>/index.html,
// a gate-passing folio landing artifact with a client-side filter box.
//
// Zero npm dependencies (Node stdlib only). Idempotent.
//
// Usage:
//   node gen-index.js                 # site-root = current directory
//   node gen-index.js <site-root>     # explicit site root
//
// Why this exists: the index derives from site.json (single source of truth).
// Hand-editing the embedded JSON drifts; this script makes regeneration one
// command, so the filter and the list stay honest.

'use strict';

const fs = require('fs');
const path = require('path');

const siteRoot = path.resolve(process.argv[2] || '.');
const manifestPath = path.join(siteRoot, '.folio', 'site.json');
const outPath = path.join(siteRoot, 'index.html');

function fail(msg) {
  process.stderr.write('gen-index: ' + msg + '\n');
  process.exit(1);
}

if (!fs.existsSync(manifestPath)) {
  fail('no .folio/site.json found under ' + siteRoot +
       '. Run this from a folio site root.');
}

let site;
try {
  site = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
} catch (e) {
  fail('could not parse ' + manifestPath + ': ' + e.message);
}

if (!site || !Array.isArray(site.artifacts)) {
  fail('site.json has no "artifacts" array');
}

// Artifact normalization — tolerate missing optional fields.
const artifacts = site.artifacts.map(function (a) {
  return {
    slug: a.slug || fail('artifact missing slug'),
    kind: a.kind || 'doc',
    bundle: a.bundle || 'single-file',
    path: a.path || ('/artifacts/' + a.slug + '/'),
    title: a.title || a.slug,
    description: a.description || '',
    ledger: Array.isArray(a.ledger) ? a.ledger : [],
    source: a.source || null,
    published_url: a.published_url || null
  };
});

const domain = site.domain || '';
const hostProfile = site.published_url ? 'surge' : 'local';
const totalDeps = artifacts.reduce(function (n, a) { return n + a.ledger.length; }, 0);
const kindCount = artifacts.reduce(function (set, a) {
  set[a.kind] = (set[a.kind] || 0) + 1; return set;
}, {});
const distinctKinds = Object.keys(kindCount).length;

// Escape dynamic text for safe innerHTML insertion.
function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Embed site.json inline, hardened against </script> breakout.
const dataJson = JSON.stringify({
  site: site.site || '',
  domain: domain,
  published_url: site.published_url || null,
  last_published: site.last_published || null,
  artifacts: artifacts
}).replace(/</g, '\\u003c');

const html = `<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(site.site || 'Folio site')}</title>
<meta name="color-scheme" content="light dark">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='6' fill='%2345577d'/%3E%3Cpath d='M7 21l5-8 4 5 3-4 6 7' fill='none' stroke='white' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E">
<style>
/* Folio · slug: ${esc(site.site || 'folio')}-index · kind: landing · bundle: single-file · host: ${hostProfile}
   deps: none · data: .folio/site.json (embedded inline) · generated by scripts/gen-index.js */

:root {
  --font-display: ui-serif, Georgia, "Iowan Old Style", serif;
  --font-body: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  --font-mono: ui-monospace, "SF Mono", Menlo, Consolas, monospace;

  --color-paper:    oklch(98% 0.006 90);
  --color-paper-2:  oklch(95% 0.008 90);
  --color-rule:     oklch(88% 0.010 90);
  --color-ink:      oklch(22% 0.020 80);
  --color-ink-2:    oklch(45% 0.012 80);
  --color-muted:    oklch(55% 0.010 80);
  --color-accent:   oklch(55% 0.180 245);
  --color-accent-ink: oklch(99% 0.004 90);
  --color-focus:    oklch(55% 0.180 245);

  --space-1: 4px; --space-2: 8px; --space-3: 12px; --space-4: 16px;
  --space-5: 24px; --space-6: 32px; --space-7: 48px; --space-8: 64px;
  --radius-sm: 4px; --radius-md: 8px; --radius-lg: 14px;
  --page-max: 960px;
}

[data-theme="dark"] {
  --color-paper:    oklch(16% 0.008 80);
  --color-paper-2:  oklch(20% 0.010 80);
  --color-rule:     oklch(30% 0.012 80);
  --color-ink:      oklch(96% 0.005 90);
  --color-ink-2:    oklch(78% 0.010 80);
  --color-muted:    oklch(68% 0.010 80);
  --color-accent:   oklch(72% 0.150 245);
  --color-accent-ink: oklch(16% 0.02 80);
  --color-focus:    oklch(74% 0.150 245);
}

*, *::before, *::after { box-sizing: border-box; }
html, body { overflow-x: clip; }
body {
  margin: 0; background: var(--color-paper); color: var(--color-ink);
  font-family: var(--font-body); font-size: 17px; line-height: 1.55;
  -webkit-font-smoothing: antialiased;
}
h1, h2, h3 { font-family: var(--font-display); font-weight: 600; line-height: 1.15; font-style: normal; margin: 0 0 var(--space-4); overflow-wrap: break-word; }
h1 { font-size: clamp(1.8rem, 5vw, 2.5rem); letter-spacing: -0.01em; }
a { color: var(--color-accent); text-decoration: none; }
a:hover { text-decoration: underline; text-underline-offset: 2px; }
code { font-family: var(--font-mono); font-size: 0.88em; }

.wrap { max-width: var(--page-max); margin: 0 auto; padding: var(--space-6) var(--space-5) var(--space-8); }

header.site-head {
  display: flex; align-items: baseline; justify-content: space-between; gap: var(--space-4);
  flex-wrap: wrap; padding-bottom: var(--space-5); border-bottom: 1px solid var(--color-rule);
}
header.site-head .lede { color: var(--color-ink-2); max-width: 56ch; }

.toggle {
  display: inline-flex; align-items: center; gap: var(--space-2);
  font-family: var(--font-body); font-size: 0.85rem; font-weight: 500;
  padding: var(--space-2) var(--space-4); border-radius: 999px;
  border: 1px solid var(--color-rule); background: var(--color-paper-2);
  color: var(--color-ink); cursor: pointer; transition: border-color .12s ease;
}
.toggle:hover { border-color: var(--color-accent); }
.toggle:focus-visible { outline: 2px solid var(--color-focus); outline-offset: 2px; }
.toggle .dot { width: 9px; height: 9px; border-radius: 50%; background: var(--color-accent); }

/* Filter bar */
.filter-bar { margin-top: var(--space-6); }
.search {
  display: flex; align-items: center; gap: var(--space-2);
  border: 1px solid var(--color-rule); border-radius: var(--radius-lg);
  background: var(--color-paper-2); padding: var(--space-2) var(--space-4);
  transition: border-color .12s ease, box-shadow .12s ease;
}
.search:focus-within { border-color: var(--color-accent); box-shadow: 0 0 0 3px oklch(55% 0.180 245 / 0.15); }
.search .icon { flex: none; color: var(--color-muted); width: 1rem; height: 1rem; }
.search input {
  flex: 1 1 auto; min-width: 0; border: none; background: transparent;
  font: inherit; color: var(--color-ink); padding: var(--space-1) 0;
}
.search input:focus { outline: none; }
.search input::placeholder { color: var(--color-muted); }
.search .kbd {
  flex: none; font-family: var(--font-mono); font-size: 0.72rem; color: var(--color-muted);
  border: 1px solid var(--color-rule); border-radius: var(--radius-sm);
  padding: 0 var(--space-2); background: var(--color-paper);
}
.result-count { color: var(--color-muted); font-size: 0.82rem; margin-top: var(--space-2); font-family: var(--font-mono); }
.result-count .num { color: var(--color-ink-2); }

.kind-group { margin-top: var(--space-6); }
.kind-group[hidden] { display: none; }
.kind-label {
  font-family: var(--font-mono); font-size: 0.72rem; text-transform: uppercase;
  letter-spacing: 0.08em; color: var(--color-muted); font-weight: 600;
  padding-bottom: var(--space-2); border-bottom: 1px solid var(--color-rule);
  margin-bottom: var(--space-3);
  display: flex; align-items: baseline; gap: var(--space-3);
}
.kind-label .count { color: var(--color-accent); font-weight: 700; }

.art-list { display: grid; gap: var(--space-2); }
.art-item {
  display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: var(--space-3);
  align-items: baseline; padding: var(--space-3) 0; border-bottom: 1px solid var(--color-rule);
}
.art-item:last-child { border-bottom: none; }
.art-item .title { font-weight: 600; color: var(--color-ink); }
.art-item .title:hover { text-decoration: underline; }
.art-item .desc { color: var(--color-muted); font-size: 0.9rem; margin-top: var(--space-1); }
.art-item .meta { color: var(--color-muted); font-size: 0.78rem; margin-top: var(--space-1); font-family: var(--font-mono); }
.art-item .slug { font-family: var(--font-mono); font-size: 0.78rem; color: var(--color-ink-2); }
.art-item[hidden] { display: none; }

.no-results { margin-top: var(--space-7); color: var(--color-muted); font-family: var(--font-mono); }
.no-results[hidden] { display: none; }

.site-footer { margin-top: var(--space-8); padding-top: var(--space-5); border-top: 1px solid var(--color-rule); font-size: 0.82rem; color: var(--color-muted); }
.site-footer code { color: var(--color-ink-2); }

@media (max-width: 480px) {
  body { font-size: 16px; }
  .wrap { padding: var(--space-5) var(--space-4) var(--space-7); }
  .art-item { grid-template-columns: minmax(0, 1fr); }
  .art-item .slug { display: none; }
  .search .kbd { display: none; }
}
</style>
</head>
<body>
<div class="wrap">

  <header class="site-head">
    <div>
      <h1>${esc(site.site || 'Folio site')}</h1>
      <p class="lede">${artifacts.length} static artifacts under one domain. Every one is a self-contained HTML file: zero external API calls, themable from one token seam. Type to filter.</p>
    </div>
    <button class="toggle" id="theme-toggle" type="button" aria-pressed="false">
      <span class="dot" aria-hidden="true"></span><span id="theme-label">Light</span>
    </button>
  </header>

  <div class="filter-bar">
    <label class="search">
      <svg class="icon" viewBox="0 0 16 16" fill="none" aria-hidden="true"><circle cx="7" cy="7" r="5" stroke="currentColor" stroke-width="1.5"/><path d="M11 11l3 3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
      <input id="filter" type="search" placeholder="Filter artifacts by title, description, or slug…" autocomplete="off" aria-label="Filter artifacts">
      <span class="kbd">/</span>
    </label>
    <div class="result-count" id="result-count" aria-live="polite"></div>
  </div>

  <main id="groups"><!-- filled by JS --></main>

  <p class="no-results" id="no-results" hidden>No artifacts match <code id="no-results-q"></code>.</p>

  <div class="site-footer">
    <p><strong>Folio</strong> · <code id="domain"></code> · Zero external deps · <code>${artifacts.length}</code> artifacts across <code>${distinctKinds}</code> kinds</p>
  </div>

</div>

<script id="site-data" type="application/json">${dataJson}</script>
<script>
(function () {
  var root = document.documentElement;
  var btn = document.getElementById('theme-toggle');
  var label = document.getElementById('theme-label');
  function apply(t) {
    root.setAttribute('data-theme', t);
    btn.setAttribute('aria-pressed', t === 'dark' ? 'true' : 'false');
    label.textContent = t === 'dark' ? 'Dark' : 'Light';
    try { localStorage.setItem('folio-site-theme', t); } catch (e) {}
  }
  var saved = null; try { saved = localStorage.getItem('folio-site-theme'); } catch (e) {}
  if (saved === 'dark' || saved === 'light') apply(saved);
  else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) apply('dark');
  btn.addEventListener('click', function () { apply(root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark'); });

  var site = JSON.parse(document.getElementById('site-data').textContent);
  document.getElementById('domain').textContent = site.domain || '(local)';

  var kindOrder = ['landing', 'doc', 'sheet', 'dashboard', 'explainer', 'slides', 'tool'];
  // Include any kinds present in data but not in the canonical order, sorted.
  Object.keys(site.artifacts.reduce(function (s, a) { s[a.kind] = 1; return s; }, {})).sort().forEach(function (k) {
    if (kindOrder.indexOf(k) === -1) kindOrder.push(k);
  });

  var groups = {};
  site.artifacts.forEach(function (a) { (groups[a.kind] = groups[a.kind] || []).push(a); });

  var groupsEl = document.getElementById('groups');
  var html = '';
  kindOrder.forEach(function (kind) {
    if (!groups[kind]) return;
    var items = groups[kind];
    html += '<section class="kind-group" data-kind="' + kind + '">';
    html += '<div class="kind-label">' + kind + ' <span class="count">' + items.length + '</span></div>';
    html += '<div class="art-list">';
    items.forEach(function (a) {
      var deps = a.ledger.length;
      var depLabel = deps === 0 ? '0 deps' : deps + ' dep' + (deps > 1 ? 's' : '');
      var remixLabel = a.source ? ' · remixed' : '';
      var q = (a.title + ' ' + a.description + ' ' + a.slug + ' ' + a.kind).toLowerCase();
      html += '<a class="art-item" href="' + a.path + '" data-q="' + q.replace(/"/g, '') + '">';
      html += '<div><div class="title">' + a.title + '</div><div class="desc">' + a.description + '</div><div class="meta">' + a.bundle + ' · ' + depLabel + remixLabel + '</div></div>';
      html += '<div class="slug">' + a.slug + '</div>';
      html += '</a>';
    });
    html += '</div></section>';
  });
  groupsEl.innerHTML = html;

  var input = document.getElementById('filter');
  var countEl = document.getElementById('result-count');
  var noRes = document.getElementById('no-results');
  var noResQ = document.getElementById('no-results-q');
  var total = site.artifacts.length;
  var allItems = [].slice.call(groupsEl.querySelectorAll('.art-item'));
  var allGroups = [].slice.call(groupsEl.querySelectorAll('.kind-group'));

  function render() {
    var q = input.value.trim().toLowerCase();
    var visible = 0;
    allItems.forEach(function (el) {
      var match = q === '' || el.getAttribute('data-q').indexOf(q) !== -1;
      el.hidden = !match;
      if (match) visible++;
    });
    allGroups.forEach(function (g) {
      var anyVisible = g.querySelectorAll('.art-item:not([hidden])').length > 0;
      g.hidden = !anyVisible;
    });
    countEl.innerHTML = '<span class="num">' + visible + '</span> of ' + total + ' artifacts';
    var empty = visible === 0;
    noRes.hidden = !empty;
    if (empty) { noResQ.textContent = input.value.trim() || '—'; }
  }
  input.addEventListener('input', render);
  render();

  // Keyboard: "/" focuses filter, Escape clears.
  document.addEventListener('keydown', function (e) {
    if (e.key === '/' && document.activeElement !== input) {
      e.preventDefault(); input.focus();
    } else if (e.key === 'Escape' && document.activeElement === input && input.value !== '') {
      input.value = ''; render(); input.focus();
    }
  });
})();
</script>
</body>
</html>
`;

fs.writeFileSync(outPath, html, 'utf8');

process.stdout.write(
  'gen-index: wrote ' + path.relative(process.cwd(), outPath) +
  ' (' + artifacts.length + ' artifacts, ' + distinctKinds + ' kinds)\n'
);
